"use client";
import { useEffect, useMemo, useState } from "react";
type DeviceInfo={label?:string;registeredAt?:string;lastSeenAt?:string;usageCount?:number};
type License={email:string;name?:string;status:string;validUntil?:string;devices:string[];deviceInfo?:Record<string,DeviceInfo>;createdAt:string;approvedAt?:string};
type Pending={requestId:string;email:string;name:string;deviceId:string;createdAt:string;expiresAt:string};
const btn:React.CSSProperties={border:"1px solid #b9c8c2",background:"white",borderRadius:9,padding:"9px 13px",fontWeight:700,cursor:"pointer"};
export default function AdminPage(){
 const [items,setItems]=useState<License[]>([]),[requests,setRequests]=useState<Pending[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(""),[query,setQuery]=useState("");
 async function load(){setError("");const r=await fetch("/api/wamifishing-admin",{cache:"no-store"});const d=await r.json();if(!r.ok){setError(d.error||"Adminbereich konnte nicht geladen werden.");return;}setItems(d.licenses||[]);setRequests(d.requests||[])}
 useEffect(()=>{void load()},[]);
 async function act(action:string,email?:string,deviceId?:string,requestId?:string){const key=action+(email||"")+(deviceId||"")+(requestId||"");setBusy(key);setError("");try{const r=await fetch("/api/wamifishing-admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,email,deviceId,requestId})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Aktion fehlgeschlagen.");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy("")}}
 function date(v?:string){return v?new Date(v).toLocaleDateString("de-DE"):"—"} function dateTime(v?:string){if(!v)return "—";const d=new Date(v);return d.toLocaleDateString("de-DE")+" · "+d.toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}
 const stats=useMemo(()=>({users:items.length,devices:items.reduce((n,u)=>n+(u.devices?.length||0),0),active:items.filter(u=>u.status==="active"&&u.validUntil&&Date.parse(u.validUntil)>Date.now()).length,pending:requests.length}),[items,requests]);
 const shown=useMemo(()=>{const q=query.trim().toLowerCase();return q?items.filter(u=>(u.name||"").toLowerCase().includes(q)||u.email.toLowerCase().includes(q)):items},[items,query]);
 return <main style={{maxWidth:1040,margin:"0 auto",padding:"24px 16px",fontFamily:"system-ui,-apple-system,sans-serif",color:"#123d35"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><small>V7.6.0</small><h1 style={{margin:"4px 0"}}>🎣 WamiFishing Administration</h1><p>Benutzer, Zugangsanfragen, Jahresfreigaben und Geräte verwalten.</p></div><a href="/" style={{background:"#087b68",color:"white",padding:"11px 16px",borderRadius:9,textDecoration:"none",fontWeight:700}}>Zur App</a></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:10,margin:"18px 0"}}>{[["Offene Anfragen",stats.pending],["Benutzer",stats.users],["Geräte",stats.devices],["Aktive Lizenzen",stats.active]].map(([label,value])=><div key={String(label)} style={{background:"white",border:"1px solid #d9e0dd",borderRadius:12,padding:"13px 14px"}}><div style={{fontSize:24,fontWeight:800}}>{value}</div><div style={{fontSize:13,color:"#62756f"}}>{label}</div></div>)}</div>
  {error&&<p style={{padding:12,background:"#fff0ef",borderRadius:10,color:"#8b1e18"}}>⚠ {error}</p>}
  <section style={{border:"1px solid #c9ddd5",borderRadius:14,padding:16,background:"#f5fbf8",marginBottom:18}}><h2 style={{marginTop:0}}>📝 Offene Zugangsanfragen <span style={{fontSize:14,fontWeight:600}}>({requests.length})</span></h2>{requests.length===0?<p style={{marginBottom:0}}>Keine offenen Anfragen.</p>:<div style={{display:"grid",gap:10}}>{requests.map(r=><div key={r.requestId} style={{background:"white",border:"1px solid #d9e0dd",borderRadius:11,padding:13,display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}><div><strong>{r.name}</strong><div>{r.email}</div><div style={{fontSize:13,color:"#62756f",marginTop:4}}>Angefragt: {dateTime(r.createdAt)}</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button style={{...btn,background:"#087b68",color:"white",borderColor:"#087b68"}} disabled={!!busy} onClick={()=>{if(confirm(`Zahlung für ${r.email} geprüft und Zugang für 1 Jahr freigeben?`))void act("approve-request",undefined,undefined,r.requestId)}}>✓ 1 Jahr freigeben</button><button style={{...btn,color:"#a21d16",borderColor:"#e1b9b6"}} disabled={!!busy} onClick={()=>{if(confirm(`Anfrage von ${r.email} ablehnen?`))void act("reject-request",undefined,undefined,r.requestId)}}>Ablehnen</button></div></div>)}</div>}</section>
  <div style={{margin:"0 0 14px"}}><label style={{fontWeight:700,display:"block"}}>Benutzer suchen<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name oder E-Mail" style={{display:"block",width:"100%",boxSizing:"border-box",marginTop:6,padding:"11px 12px",border:"1px solid #b9c8c2",borderRadius:9,fontSize:16}}/></label></div>
  <div style={{display:"grid",gap:14}}>{shown.map(u=><section key={u.email} style={{border:"1px solid #d9e0dd",borderRadius:14,padding:16,background:"white"}}>
   <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong style={{fontSize:18}}>{u.name||u.email}</strong>{u.name&&<div>{u.email}</div>}<div style={{marginTop:6}}>Status: <strong>{u.status}</strong> · gültig bis <strong>{date(u.validUntil)}</strong></div></div><div><strong>{u.devices?.length||0}/3 Geräte</strong></div></div>
   <div style={{display:"grid",gap:9,marginTop:14}}>{(u.devices||[]).map((d,i)=>{const info=u.deviceInfo?.[d];return <div key={d} style={{display:"flex",gap:12,alignItems:"center",justifyContent:"space-between",padding:"12px 13px",background:"#f1f6f3",borderRadius:10,flexWrap:"wrap"}}><div><div style={{fontWeight:800,fontSize:16}}>{info?.label==="iPhone"?"📱":info?.label==="iPad"?"📱":info?.label?.includes("Windows")?"💻":"🖥️"} {info?.label||`Gerät ${i+1}`}</div><div style={{fontSize:13,color:"#62756f",marginTop:3}}>Registriert: {info?.registeredAt?dateTime(info.registeredAt):"vor V7.5.1"} · zuletzt aktiv: {dateTime(info?.lastSeenAt)}</div><div style={{fontSize:13,color:"#355e55",marginTop:3,fontWeight:700}}>Nutzungen: {info?.usageCount??0}</div><details style={{fontSize:12,color:"#70827c",marginTop:3}}><summary style={{cursor:"pointer"}}>Geräte-ID anzeigen</summary><span style={{wordBreak:"break-all"}}>{d}</span></details></div><button style={btn} disabled={!!busy} onClick={()=>{if(confirm(`${info?.label||`Gerät ${i+1}`} von ${u.email} wirklich entfernen?`))void act("remove-device",u.email,d)}}>Gerät entfernen</button></div>})}</div>
   <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:14}}><button style={btn} disabled={!!busy} onClick={()=>void act("extend-year",u.email)}>+ 1 Jahr</button>{u.status==="active"?<button style={btn} disabled={!!busy} onClick={()=>{if(confirm(`${u.email} wirklich sperren?`))void act("block",u.email)}}>Sperren</button>:<button style={btn} disabled={!!busy} onClick={()=>void act("activate",u.email)}>Freigeben</button>}<button style={{...btn,color:"#a21d16",borderColor:"#e1b9b6"}} disabled={!!busy} onClick={()=>{if(confirm(`Benutzer ${u.email} wirklich löschen?\n\nCloud-Fangdaten werden dabei NICHT gelöscht.`))void act("delete-user",u.email)}}>Benutzer löschen</button></div>
  </section>)}{!shown.length&&!error&&<p>{query?"Keine passenden Benutzer gefunden.":"Benutzer werden geladen …"}</p>}</div>
 </main>;
}
