import { requireWamiUser } from "../_wamifishing-auth";
import { get, put } from "@vercel/blob";
export const runtime="nodejs"; export const dynamic="force-dynamic";
type Friend={userId:string;name:string;friendCode:string}; type Profile={userId:string;name:string;friendCode:string;friends:Friend[]};
type Item={id:string;visibility?:"private"|"friends"|"public";[key:string]:unknown}; type Doc={userId:string;ownerName:string;catches:Item[];parkings:Item[];hotspots:Item[];updatedAt:string};
function pp(id:string){return `wamifishing/social/profiles/${id}.json`} function sp(id:string){return `wamifishing/social/shared/${id}.json`}
async function read<T>(p:string):Promise<T|null>{try{const r=await get(p,{access:"private",useCache:false});return r?JSON.parse(await new Response(r.stream).text()) as T:null}catch(e){if(/404|not found/i.test(e instanceof Error?e.message:String(e)))return null;throw e}} async function write(p:string,v:unknown){await put(p,JSON.stringify(v),{access:"private",allowOverwrite:true,contentType:"application/json; charset=utf-8"})}
function safe(v:unknown):Item[]{return Array.isArray(v)?v.filter((x):x is Item=>!!x&&typeof x==="object"&&typeof (x as Item).id==="string"&&["friends","public"].includes(String((x as Item).visibility))):[]}
export async function PUT(r:Request){try{const identity=await requireWamiUser(r);if(!identity)return Response.json({error:"Bitte per E-Mail anmelden."},{status:401});const id=identity.dataUserId;const p=await read<Profile>(pp(id));if(!p)return Response.json({error:"Bitte zuerst Freundeprofil speichern."},{status:400});const b=await r.json() as Record<string,unknown>;await write(sp(id),{userId:id,ownerName:p.name,catches:safe(b.catches),parkings:safe(b.parkings),hotspots:safe(b.hotspots),updatedAt:new Date().toISOString()});return Response.json({ok:true})}catch(e){console.error(e);return Response.json({error:"Freigaben konnten nicht gespeichert werden."},{status:500})}}
export async function GET(r:Request){try{const identity=await requireWamiUser(r);if(!identity)return Response.json({error:"Bitte per E-Mail anmelden."},{status:401});const id=identity.dataUserId;const me=await read<Profile>(pp(id));if(!me)return Response.json({catches:[],parkings:[],hotspots:[]});const catches:any[]=[],parkings:any[]=[],hotspots:any[]=[];for(const f of me.friends??[]){const d=await read<Doc>(sp(f.userId));if(!d)continue;for(const x of d.catches??[])if(x.visibility==="friends"||x.visibility==="public")catches.push({...x,ownerId:d.userId,ownerName:d.ownerName});for(const x of d.parkings??[])if(x.visibility==="friends"||x.visibility==="public")parkings.push({...x,ownerId:d.userId,ownerName:d.ownerName});for(const x of d.hotspots??[])if(x.visibility==="friends"||x.visibility==="public")hotspots.push({...x,ownerId:d.userId,ownerName:d.ownerName})}return Response.json({catches,parkings,hotspots},{headers:{"Cache-Control":"no-store"}})}catch(e){console.error(e);return Response.json({error:"Freigaben konnten nicht gelesen werden."},{status:500})}}
