import { requireWamiUser } from "../_wamifishing-auth";
import { get, put, list } from "@vercel/blob";
export const runtime="nodejs"; export const dynamic="force-dynamic";
type Friend={userId:string;name:string;friendCode:string}; type Profile={userId:string;name:string;friendCode:string;friends:Friend[]};
type Item={id:string;visibility?:"private"|"friends"|"public";[key:string]:unknown}; type Doc={userId:string;ownerName:string;catches:Item[];parkings:Item[];hotspots:Item[];updatedAt:string};
function pp(id:string){return `wamifishing/social/profiles/${id}.json`} function sp(id:string){return `wamifishing/social/shared/${id}.json`}
async function read<T>(p:string):Promise<T|null>{try{const r=await get(p,{access:"private",useCache:false});return r?JSON.parse(await new Response(r.stream).text()) as T:null}catch(e){if(/404|not found/i.test(e instanceof Error?e.message:String(e)))return null;throw e}} async function write(p:string,v:unknown){await put(p,JSON.stringify(v),{access:"private",allowOverwrite:true,contentType:"application/json; charset=utf-8"})}
function safe(v:unknown):Item[]{return Array.isArray(v)?v.filter((x):x is Item=>!!x&&typeof x==="object"&&typeof (x as Item).id==="string"&&["friends","public"].includes(String((x as Item).visibility))):[]}
export async function PUT(r:Request){try{const identity=await requireWamiUser(r);if(!identity)return Response.json({error:"Bitte per E-Mail anmelden."},{status:401});const id=identity.dataUserId;const p=await read<Profile>(pp(id));if(!p)return Response.json({error:"Bitte zuerst Freundeprofil speichern."},{status:400});const b=await r.json() as Record<string,unknown>;await write(sp(id),{userId:id,ownerName:p.name,catches:safe(b.catches),parkings:safe(b.parkings),hotspots:safe(b.hotspots),updatedAt:new Date().toISOString()});return Response.json({ok:true})}catch(e){console.error(e);return Response.json({error:"Freigaben konnten nicht gespeichert werden."},{status:500})}}
export async function GET(r:Request){try{const identity=await requireWamiUser(r);if(!identity)return Response.json({error:"Bitte per E-Mail anmelden."},{status:401});const id=identity.dataUserId;const me=await read<Profile>(pp(id));if(!me)return Response.json({catches:[],parkings:[],hotspots:[]});const catches:any[]=[],parkings:any[]=[],hotspots:any[]=[];const friendIds=new Set((me.friends??[]).map(f=>f.userId));
  const seen=new Set<string>();
  async function addDoc(d:Doc|null){if(!d||d.userId===id||seen.has(d.userId))return;seen.add(d.userId);const isFriend=friendIds.has(d.userId);for(const x of d.catches??[])if(x.visibility==="public"||(isFriend&&x.visibility==="friends"))catches.push({...x,ownerId:d.userId,ownerName:d.ownerName});for(const x of d.parkings??[])if(x.visibility==="public"||(isFriend&&x.visibility==="friends"))parkings.push({...x,ownerId:d.userId,ownerName:d.ownerName});for(const x of d.hotspots??[])if(x.visibility==="public"||(isFriend&&x.visibility==="friends"))hotspots.push({...x,ownerId:d.userId,ownerName:d.ownerName})}
  for(const f of me.friends??[])await addDoc(await read<Doc>(sp(f.userId)));
  let cursor: string|undefined=undefined;do{const page=await list({prefix:"wamifishing/social/shared/",cursor,limit:100});for(const blob of page.blobs){const m=blob.pathname.match(/shared\/([^/]+)\.json$/);if(m&&!seen.has(m[1])&&m[1]!==id)await addDoc(await read<Doc>(blob.pathname))}cursor=page.hasMore?page.cursor:undefined}while(cursor);
  return Response.json({catches,parkings,hotspots},{headers:{"Cache-Control":"no-store"}})}catch(e){console.error(e);return Response.json({error:"Freigaben konnten nicht gelesen werden."},{status:500})}}
