import { del, list } from "@vercel/blob";
import { authUserId, licensePath, readJson, readLicense, sessionPath, writeJson, writeLicense } from "../_wamifishing-auth";
export const runtime="nodejs"; export const dynamic="force-dynamic"; const MAX_DEVICES=3;
type Session={email:string;authUserId:string;dataUserId:string;deviceId:string;expiresAt:string};
type DeviceInfo={label?:string;registeredAt?:string;lastSeenAt?:string;usageCount?:number};
type License={email:string;name?:string;authUserId:string;status:"pending"|"active"|"rejected"|"expired";validUntil?:string;devices:string[];deviceInfo?:Record<string,DeviceInfo>;createdAt:string;approvedAt?:string};
type Pending={email:string;name:string;deviceId:string;dataUserId:string;adminTokenHash:string;createdAt:string;expiresAt:string};
type PendingAdmin=Pending&{requestId:string};
type DeletionRequest={authUserId:string;dataUserId:string;email:string;requestedAt:string;status:"pending"};
function norm(v:unknown){return String(v??"").trim().toLowerCase()}
function cookieValue(request:Request,name:string){const raw=request.headers.get("cookie")??"";for(const part of raw.split(";")){const [key,...rest]=part.trim().split("=");if(key===name)return decodeURIComponent(rest.join("="));}return ""}
async function isAdmin(request:Request){const token=cookieValue(request,"wami_session");if(!token)return false;const session=await readJson<Session>(sessionPath(token));if(!session||Date.parse(session.expiresAt)<=Date.now())return false;const admin=norm(process.env.WAMI_ADMIN_EMAIL);if(!admin||norm(session.email)!==admin)return false;const lic=await readLicense(session.email);return Boolean(lic?.status==="active"&&lic.validUntil&&Date.parse(lic.validUntil)>Date.now()&&lic.devices.includes(session.deviceId));}
async function allJson<T>(prefix:string){const out:T[]=[];let cursor:string|undefined;do{const r=await list({prefix,cursor,limit:1000});for(const b of r.blobs){const v=await readJson<T>(b.pathname);if(v)out.push(v);}cursor=r.hasMore?r.cursor:undefined;}while(cursor);return out;}
async function deletePrefix(prefix:string){let cursor:string|undefined;do{const r=await list({prefix,cursor,limit:1000});if(r.blobs.length)await del(r.blobs.map(b=>b.pathname));cursor=r.hasMore?r.cursor:undefined;}while(cursor);}
async function deletionRequests(){return allJson<DeletionRequest>("wamifishing/privacy/deletion-requests/");}
async function purgeUser(email:string,dataUserId:string){
 const id=authUserId(email); const profile=await readJson<any>(`wamifishing/social/profiles/${dataUserId}.json`);
 if(profile?.friendCode)await del(`wamifishing/social/codes/${String(profile.friendCode).toUpperCase()}.json`).catch(()=>undefined);
 const profiles=await allJson<any>("wamifishing/social/profiles/");
 for(const other of profiles){if(!other?.userId||other.userId===dataUserId)continue;const friends=Array.isArray(other.friends)?other.friends.filter((f:any)=>f?.userId!==dataUserId):[];const incoming=Array.isArray(other.incoming)?other.incoming.filter((r:any)=>r?.fromUserId!==dataUserId):[];if(friends.length!==(other.friends??[]).length||incoming.length!==(other.incoming??[]).length)await writeJson(`wamifishing/social/profiles/${other.userId}.json`,{...other,friends,incoming,updatedAt:new Date().toISOString()});}
 await Promise.all([deletePrefix(`wamifishing/users/${dataUserId}/`),del(`wamifishing/social/profiles/${dataUserId}.json`).catch(()=>undefined),del(`wamifishing/social/shared/${dataUserId}.json`).catch(()=>undefined),del(`wamifishing/auth/users/${id}.json`).catch(()=>undefined),del(`wamifishing/privacy/deletion-requests/${id}.json`).catch(()=>undefined)]);
 const sessions=await allJson<any>("wamifishing/auth/sessions/");let cursor:string|undefined;do{const r=await list({prefix:"wamifishing/auth/sessions/",cursor,limit:1000});for(const b of r.blobs){const v=await readJson<any>(b.pathname);if(v?.email&&norm(v.email)===norm(email))await del(b.pathname).catch(()=>undefined);}cursor=r.hasMore?r.cursor:undefined;}while(cursor);
 let rc:string|undefined;do{const r=await list({prefix:"wamifishing/auth/requests/",cursor:rc,limit:1000});for(const b of r.blobs){const v=await readJson<any>(b.pathname);if(v?.email&&norm(v.email)===norm(email))await del(b.pathname).catch(()=>undefined);}rc=r.hasMore?r.cursor:undefined;}while(rc);
 await del(licensePath(email)).catch(()=>undefined);
}
async function pendingRequests(){const out:PendingAdmin[]=[];let cursor:string|undefined;do{const r=await list({prefix:"wamifishing/auth/requests/",cursor,limit:1000});for(const b of r.blobs){const v=await readJson<Pending>(b.pathname);if(!v||Date.parse(v.expiresAt)<=Date.now())continue;const requestId=b.pathname.split("/").pop()?.replace(/\.json$/i,"")||"";if(requestId)out.push({...v,requestId});}cursor=r.hasMore?r.cursor:undefined;}while(cursor);return out.sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt));}
function safeDevice(v:unknown){const s=String(v??"").trim();return /^[A-Za-z0-9_-]{8,120}$/.test(s)?s:""}
function deviceLabel(request:Request){const ua=request.headers.get("user-agent")||"";if(/iPhone/i.test(ua))return "iPhone";if(/iPad/i.test(ua))return "iPad";if(/Android/i.test(ua))return /Mobile/i.test(ua)?"Android-Smartphone":"Android-Tablet";if(/Windows/i.test(ua))return "Windows-PC";if(/Macintosh|Mac OS X/i.test(ua))return "Mac";if(/Linux/i.test(ua))return "Linux-PC";return "Gerät";}
async function bindUser(email:string,dataUserId:string){const id=authUserId(email);const p=`wamifishing/auth/users/${id}.json`;const existing=await readJson<{dataUserId:string}>(p);if(!existing)await writeJson(p,{dataUserId,email,boundAt:new Date().toISOString()});return existing?.dataUserId||dataUserId;}
export async function GET(request:Request){if(!await isAdmin(request))return Response.json({error:"Nicht berechtigt."},{status:403});const [licenses,requests,deletions]=await Promise.all([allJson<License>("wamifishing/auth/licenses/"),pendingRequests(),deletionRequests()]);licenses.sort((a,b)=>a.email.localeCompare(b.email,"de"));return Response.json({ok:true,maxDevices:MAX_DEVICES,licenses,requests,deletions},{headers:{"Cache-Control":"no-store"}});}
export async function POST(request:Request){if(!await isAdmin(request))return Response.json({error:"Nicht berechtigt."},{status:403});try{const b=await request.json() as Record<string,unknown>;const action=String(b.action??"");
 if(action==="approve-request"||action==="reject-request"){
  const requestId=String(b.requestId??"").trim();if(!/^[a-f0-9]{64}$/i.test(requestId))return Response.json({error:"Anfrage-ID fehlt."},{status:400});
  const path=`wamifishing/auth/requests/${requestId}.json`;const p=await readJson<Pending>(path);if(!p||Date.parse(p.expiresAt)<=Date.now())return Response.json({error:"Diese Anfrage ist bereits erledigt oder abgelaufen."},{status:409});
  await writeJson(path,{...p,expiresAt:new Date(0).toISOString()});const old=await readLicense(p.email);const now=new Date();const id=authUserId(p.email);
  if(action==="reject-request"){if(!old)await writeLicense({email:p.email,name:p.name,authUserId:id,status:"rejected",devices:[],createdAt:now.toISOString()});return Response.json({ok:true});}
  const devices=Array.from(new Set(old?.devices??[]));if(!devices.includes(p.deviceId)&&devices.length>=MAX_DEVICES)return Response.json({error:`Für dieses Konto sind bereits ${MAX_DEVICES} Geräte registriert.`},{status:409});if(!devices.includes(p.deviceId))devices.push(p.deviceId);
  const oldValid=old?.status==="active"&&old.validUntil&&Date.parse(old.validUntil)>Date.now();const valid=oldValid?new Date(old!.validUntil!):new Date(now);if(!oldValid)valid.setFullYear(valid.getFullYear()+1);
  const info={...(old?.deviceInfo??{})};const previous=info[p.deviceId]??{};info[p.deviceId]={...previous,label:previous.label||"Gerät",registeredAt:previous.registeredAt||now.toISOString(),lastSeenAt:previous.lastSeenAt||now.toISOString(),usageCount:previous.usageCount??0};
  await writeLicense({email:p.email,name:p.name||old?.name,authUserId:id,status:"active",validUntil:valid.toISOString(),devices,deviceInfo:info,createdAt:old?.createdAt??now.toISOString(),approvedAt:now.toISOString()});await bindUser(p.email,p.dataUserId);return Response.json({ok:true,validUntil:valid.toISOString()});
 }
 const email=norm(b.email);if(!email)return Response.json({error:"E-Mail fehlt."},{status:400});const lic=await readLicense(email);if(!lic)return Response.json({error:"Benutzer nicht gefunden."},{status:404});
 if(action==="remove-device"){const deviceId=safeDevice(b.deviceId);if(!deviceId)return Response.json({error:"Geräte-ID fehlt."},{status:400});const info={...(lic.deviceInfo??{})};delete info[deviceId];await writeLicense({...lic,devices:(lic.devices??[]).filter(x=>x!==deviceId),deviceInfo:info});return Response.json({ok:true});}
 if(action==="extend-year"){const base=lic.validUntil&&Date.parse(lic.validUntil)>Date.now()?new Date(lic.validUntil):new Date();base.setFullYear(base.getFullYear()+1);await writeLicense({...lic,status:"active",validUntil:base.toISOString(),approvedAt:lic.approvedAt??new Date().toISOString()});return Response.json({ok:true});}
 if(action==="block"){await writeLicense({...lic,status:"rejected"});return Response.json({ok:true});}
 if(action==="activate"){let until=lic.validUntil&&Date.parse(lic.validUntil)>Date.now()?lic.validUntil:"";if(!until){const d=new Date();d.setFullYear(d.getFullYear()+1);until=d.toISOString();}await writeLicense({...lic,status:"active",validUntil:until});return Response.json({ok:true});}
 if(action==="delete-user"){await del([licensePath(email),`wamifishing/auth/users/${authUserId(email)}.json`]);return Response.json({ok:true});}
 if(action==="reject-deletion"){await del(`wamifishing/privacy/deletion-requests/${authUserId(email)}.json`).catch(()=>undefined);return Response.json({ok:true});}
 if(action==="delete-user-data"){const binding=await readJson<{dataUserId:string}>(`wamifishing/auth/users/${authUserId(email)}.json`);if(!binding?.dataUserId)return Response.json({error:"Datenkonto nicht gefunden."},{status:404});await purgeUser(email,binding.dataUserId);return Response.json({ok:true});}
 return Response.json({error:"Unbekannte Aktion."},{status:400});}catch(e){console.error("WamiFishing Admin:",e);return Response.json({error:e instanceof Error?e.message:String(e)},{status:500});}}
