import { del, list } from "@vercel/blob";
import { authUserId, licensePath, readJson, readLicense, sessionPath, writeLicense } from "../_wamifishing-auth";
export const runtime="nodejs"; export const dynamic="force-dynamic"; const MAX_DEVICES=3;
type Session={email:string;authUserId:string;dataUserId:string;deviceId:string;expiresAt:string};
type DeviceInfo={label?:string;registeredAt?:string;lastSeenAt?:string};
type License={email:string;name?:string;authUserId:string;status:"pending"|"active"|"rejected"|"expired";validUntil?:string;devices:string[];deviceInfo?:Record<string,DeviceInfo>;createdAt:string;approvedAt?:string};
function norm(v:unknown){return String(v??"").trim().toLowerCase()}
function cookieValue(request:Request,name:string){const raw=request.headers.get("cookie")??"";for(const part of raw.split(";")){const [key,...rest]=part.trim().split("=");if(key===name)return decodeURIComponent(rest.join("="));}return ""}
async function isAdmin(request:Request){const token=cookieValue(request,"wami_session");if(!token)return false;const session=await readJson<Session>(sessionPath(token));if(!session||Date.parse(session.expiresAt)<=Date.now())return false;const admin=norm(process.env.WAMI_ADMIN_EMAIL);if(!admin||norm(session.email)!==admin)return false;const lic=await readLicense(session.email);return Boolean(lic?.status==="active"&&lic.validUntil&&Date.parse(lic.validUntil)>Date.now()&&lic.devices.includes(session.deviceId));}
async function allJson<T>(prefix:string){const out:T[]=[];let cursor:string|undefined;do{const r=await list({prefix,cursor,limit:1000});for(const b of r.blobs){const v=await readJson<T>(b.pathname);if(v)out.push(v);}cursor=r.hasMore?r.cursor:undefined;}while(cursor);return out;}
function safeDevice(v:unknown){const s=String(v??"").trim();return /^[A-Za-z0-9_-]{8,120}$/.test(s)?s:""}
export async function GET(request:Request){if(!await isAdmin(request))return Response.json({error:"Nicht berechtigt."},{status:403});const licenses=(await allJson<License>("wamifishing/auth/licenses/")).sort((a,b)=>a.email.localeCompare(b.email,"de"));return Response.json({ok:true,maxDevices:MAX_DEVICES,licenses},{headers:{"Cache-Control":"no-store"}});}
export async function POST(request:Request){if(!await isAdmin(request))return Response.json({error:"Nicht berechtigt."},{status:403});try{const b=await request.json() as Record<string,unknown>;const action=String(b.action??"");const email=norm(b.email);if(!email)return Response.json({error:"E-Mail fehlt."},{status:400});const lic=await readLicense(email);if(!lic)return Response.json({error:"Benutzer nicht gefunden."},{status:404});if(action==="remove-device"){const deviceId=safeDevice(b.deviceId);if(!deviceId)return Response.json({error:"Geräte-ID fehlt."},{status:400});const info={...(lic.deviceInfo??{})};delete info[deviceId];await writeLicense({...lic,devices:(lic.devices??[]).filter(x=>x!==deviceId),deviceInfo:info});return Response.json({ok:true});}if(action==="extend-year"){const base=lic.validUntil&&Date.parse(lic.validUntil)>Date.now()?new Date(lic.validUntil):new Date();base.setFullYear(base.getFullYear()+1);await writeLicense({...lic,status:"active",validUntil:base.toISOString(),approvedAt:lic.approvedAt??new Date().toISOString()});return Response.json({ok:true});}if(action==="block"){await writeLicense({...lic,status:"rejected"});return Response.json({ok:true});}if(action==="activate"){let until=lic.validUntil&&Date.parse(lic.validUntil)>Date.now()?lic.validUntil:"";if(!until){const d=new Date();d.setFullYear(d.getFullYear()+1);until=d.toISOString();}await writeLicense({...lic,status:"active",validUntil:until});return Response.json({ok:true});}if(action==="delete-user"){await del([licensePath(email),`wamifishing/auth/users/${authUserId(email)}.json`]);return Response.json({ok:true});}return Response.json({error:"Unbekannte Aktion."},{status:400});}catch(e){console.error("WamiFishing Admin:",e);return Response.json({error:e instanceof Error?e.message:String(e)},{status:500});}}
