// AUTO-GENERATED by scripts/import-atkis-hydro.mjs
// Source: OpenStreetMap contributors (ODbL), Nominatim and Overpass API

export interface AtkisWaterMatch {
  status: "matched" | "review" | "unmatched";
  latitude?: number; longitude?: number; confidence?: number;
  method?: "nominatim-name" | "overpass-locality";
  officialName?: string; officialFeatureId?: string; officialTypeName?: string;
  areaHa?: number; distanceKm?: number; source?: string; checkedAt?: string; matchedAlias?: string;
}

export const atkisWaterMatchIndex: Record<string, AtkisWaterMatch> = {
  "1-160-01-bruders-teich-bei-gardelegen": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:45:53.124Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "1-160-02-wasserspeicher-luffingen": {
    "status": "review",
    "latitude": 52.5779873,
    "longitude": 11.4170786,
    "confidence": 0.771,
    "method": "nominatim-name",
    "officialName": "Lüffingen",
    "matchedAlias": "luffingen",
    "officialFeatureId": "relation/5298560",
    "officialTypeName": "nominatim:unknown",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API",
    "checkedAt": "2026-08-06T11:45:55.892Z"
  },
  "1-160-03-kieskuhle-die-lange-wohrde": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:46:01.868Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "1-160-04-stadtgraben-in-gardelegen": {
    "status": "review",
    "latitude": 52.5252862,
    "longitude": 11.3885876,
    "confidence": 0.819,
    "method": "nominatim-name",
    "officialName": "Stadtgraben",
    "matchedAlias": "Stadtgraben",
    "officialFeatureId": "relation/1330736",
    "officialTypeName": "nominatim:standing",
    "distanceKm": 0.34,
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API",
    "checkedAt": "2026-08-06T11:46:08.101Z"
  },
  "1-160-05-lindenthaler-teich-bei-gardelegen": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:46:13.614Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "1-160-06-wilhelmskanal-von-strae": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:46:19.176Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "1-160-07-rotzen-s-loch-bei-breiteiche": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:46:23.769Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "1-160-08-kiessee-gade-bei-solpke": {
    "status": "matched",
    "latitude": 52.4834015,
    "longitude": 11.281997,
    "confidence": 0.932,
    "method": "nominatim-name",
    "officialName": "Kiessee Gäde",
    "matchedAlias": "Kiessee Gäde",
    "officialFeatureId": "relation/3074557",
    "officialTypeName": "nominatim:standing",
    "distanceKm": 2.38,
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API",
    "checkedAt": "2026-08-06T11:46:29.331Z"
  },
  "1-160-09-5-teiche-am-ipser-weg": {
    "status": "review",
    "latitude": 52.5121191,
    "longitude": 11.3984486,
    "confidence": 0.658,
    "method": "nominatim-name",
    "officialName": "Ipser Weg",
    "matchedAlias": "5 ipser weg",
    "officialFeatureId": "way/41111937",
    "officialTypeName": "nominatim:unknown",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API",
    "checkedAt": "2026-08-06T11:46:34.123Z"
  },
  "1-160-12-mahlbusen-heidberg-bei-estedt": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:46:58.924Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "6-401-02-bruch-2-bei-breitenhagen": {
    "status": "review",
    "latitude": 51.9227195,
    "longitude": 11.9340061,
    "confidence": 0.978,
    "method": "overpass-locality",
    "officialName": "Bruch 1",
    "matchedAlias": "Bruch 2",
    "officialFeatureId": "way/95936511",
    "officialTypeName": "overpass:standing",
    "distanceKm": 0.75,
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API",
    "checkedAt": "2026-08-06T11:47:51.668Z"
  },
  "6-401-03-bruch-3-bei-breitenhagen": {
    "status": "review",
    "latitude": 51.9227195,
    "longitude": 11.9340061,
    "confidence": 0.978,
    "method": "overpass-locality",
    "officialName": "Bruch 1",
    "matchedAlias": "Bruch 3",
    "officialFeatureId": "way/95936511",
    "officialTypeName": "overpass:standing",
    "distanceKm": 0.75,
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API",
    "checkedAt": "2026-08-06T11:47:58.680Z"
  },
  "6-401-04-badebruch-bei-breitenhagen": {
    "status": "matched",
    "latitude": 51.9224582,
    "longitude": 11.9352462,
    "confidence": 0.981,
    "method": "nominatim-name",
    "officialName": "Badebruch",
    "matchedAlias": "Badebruch",
    "officialFeatureId": "way/95936509",
    "officialTypeName": "nominatim:standing",
    "distanceKm": 0.68,
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API",
    "checkedAt": "2026-08-06T11:48:05.236Z"
  },
  "6-401-05-drahningensee-bei-breitenhagen": {
    "status": "review",
    "latitude": 51.9195745,
    "longitude": 11.9527659,
    "confidence": 0.497,
    "method": "overpass-locality",
    "officialName": "Graben von Breitenhagen",
    "matchedAlias": "Drähningensee bei Breitenhagen",
    "officialFeatureId": "way/1526121027",
    "officialTypeName": "overpass:flow",
    "distanceKm": 0.77,
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API",
    "checkedAt": "2026-08-06T11:48:12.277Z"
  },
  "6-401-06-krugersee-bei-breitenhagen": {
    "status": "matched",
    "latitude": 51.9055235,
    "longitude": 11.9390952,
    "confidence": 0.939,
    "method": "nominatim-name",
    "officialName": "Krügersee",
    "matchedAlias": "Krügersee",
    "officialFeatureId": "way/23874630",
    "officialTypeName": "nominatim:standing",
    "distanceKm": 2.13,
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API",
    "checkedAt": "2026-08-06T11:48:19.059Z"
  },
  "6-401-07-kleiner-dorfsee-gro-rosenburg": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:48:22.523Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "6-401-08-landgraben-von-einmundung-des": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:48:29.983Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "6-401-09-taube-von-700m-oberhalb-der": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:48:34.936Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "6-402-01-dolphus-bei-barby": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:48:52.221Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "6-402-02-barbyer-landgraben-von": {
    "status": "review",
    "latitude": 52.0479521,
    "longitude": 11.7413616,
    "confidence": 0.5,
    "method": "overpass-locality",
    "officialName": "Elbenauer Landgraben",
    "matchedAlias": "Barbyer Landgraben von",
    "officialFeatureId": "way/38568595",
    "officialTypeName": "overpass:flow",
    "distanceKm": 3.02,
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API",
    "checkedAt": "2026-08-06T11:49:23.101Z"
  },
  "6-402-03-hafen-barby": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:49:27.968Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "6-402-04-kiesgrube-barby-sud": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:49:30.985Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "6-402-06-restloch-konigsaue": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:49:33.835Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "6-402-07-saale-von-werkleitz-bis-elbmundung": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:49:38.591Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "6-410-01-schachte-bei-tarthun": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:50:06.626Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "6-410-02-warmsdorfer-teich": {
    "status": "review",
    "latitude": 51.781474,
    "longitude": 11.5874465,
    "confidence": 0.606,
    "method": "nominatim-name",
    "officialName": "Warmsdorfer Weg",
    "matchedAlias": "warmsdorfer",
    "officialFeatureId": "way/33889900",
    "officialTypeName": "nominatim:unknown",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API",
    "checkedAt": "2026-08-06T11:50:09.700Z"
  },
  "6-410-03-ritterflurteich-bei-stafurt": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:50:38.973Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  },
  "6-410-04-stockscher-teich-bei-wolmirsleben": {
    "status": "unmatched",
    "checkedAt": "2026-08-06T11:53:37.087Z",
    "source": "OpenStreetMap contributors (ODbL), Nominatim and Overpass API"
  }
};
