// AUTO-GENERATED by scripts/verify-two-source-v6.mjs
export const twoSourceWaterV6Index = {
  "1-160-01-bruders-teich-bei-gardelegen": {
    "status": "review",
    "latitude": 52.5298075,
    "longitude": 11.3967719,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-02-wasserspeicher-luffingen": {
    "status": "review",
    "latitude": 52.5690667,
    "longitude": 11.4038551,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-03-kieskuhle-die-lange-wohrde": {
    "status": "review",
    "latitude": 52.5298075,
    "longitude": 11.3967719,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-04-stadtgraben-in-gardelegen": {
    "status": "review",
    "latitude": 52.5186616,
    "longitude": 11.3838142,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-05-lindenthaler-teich-bei-gardelegen": {
    "status": "review",
    "latitude": 52.5298075,
    "longitude": 11.3967719,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-06-wilhelmskanal-von-strae": {
    "status": "unmatched",
    "reason": "Kein OSM-v3-Kandidat zum Gegenprüfen."
  },
  "1-160-07-rotzen-s-loch-bei-breiteiche": {
    "status": "unmatched",
    "reason": "Kein OSM-v3-Kandidat zum Gegenprüfen."
  },
  "1-160-08-kiessee-gade-bei-solpke": {
    "status": "review",
    "latitude": 52.5072174,
    "longitude": 11.3007939,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-09-5-teiche-am-ipser-weg": {
    "status": "review",
    "latitude": 52.5105546,
    "longitude": 11.4031394,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-12-mahlbusen-heidberg-bei-estedt": {
    "status": "review",
    "latitude": 52.5774526,
    "longitude": 11.3662233,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-13-forsterteich-bei-jerchel": {
    "status": "review",
    "latitude": 52.4660874,
    "longitude": 11.3160803,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-14-milde-von-gardelegen": {
    "status": "review",
    "latitude": 52.5194852,
    "longitude": 11.5303351,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-15-blechbudenteich-bei": {
    "status": "review",
    "latitude": 52.69358,
    "longitude": 11.4673365,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-16-untere-milde-von-wegebrucke": {
    "status": "review",
    "latitude": 52.7047934,
    "longitude": 11.5078816,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-17-kellerbuschteiche-lindstedt": {
    "status": "review",
    "latitude": 52.5905802,
    "longitude": 11.5322808,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-18-untere-milde-von-straenbrucke": {
    "status": "unmatched",
    "reason": "Kein OSM-v3-Kandidat zum Gegenprüfen."
  },
  "1-160-19-teich-faule-breite-bei-letzlingen": {
    "status": "review",
    "latitude": 52.4460723,
    "longitude": 11.4729848,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-20-konigsgraben-vom-abschlag": {
    "status": "review",
    "latitude": 52.7047934,
    "longitude": 11.5078816,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-21-kiesgrube-wernitz": {
    "status": "review",
    "latitude": 52.4877963,
    "longitude": 11.2364454,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-22-secantsgraben-von-str-br-kalbe-m": {
    "status": "review",
    "latitude": 52.7047934,
    "longitude": 11.5078816,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-160-23-grube-minna-bei-kassieck": {
    "status": "review",
    "latitude": 52.5846956,
    "longitude": 11.4873324,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-161-01-teich-am-anglerheim-burggraben": {
    "status": "review",
    "latitude": 51.773576,
    "longitude": 10.7971424,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-161-02-milde-von-kalbe-straenbrucke": {
    "status": "unmatched",
    "reason": "Kein OSM-v3-Kandidat zum Gegenprüfen."
  },
  "1-161-03-untere-milde-von-winkelstedt": {
    "status": "review",
    "latitude": 52.677317,
    "longitude": 11.3072696,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-01-dorfteich-miesterhorst": {
    "status": "review",
    "latitude": 52.460807,
    "longitude": 11.1415221,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-02-anglerteiche-apenburg": {
    "status": "review",
    "latitude": 52.7100588,
    "longitude": 11.2006718,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-03-wasserbecken-am-schlammgraben": {
    "status": "review",
    "latitude": 52.5761761,
    "longitude": 11.0779017,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-04-prozebusch-in-dannefeld": {
    "status": "review",
    "latitude": 52.5076908,
    "longitude": 11.1432105,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-05-sauergrund-bei-dannefeld": {
    "status": "review",
    "latitude": 52.5076908,
    "longitude": 11.1432105,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-07-beregnungsteich-bei-lockstedt": {
    "status": "review",
    "latitude": 52.6657464,
    "longitude": 11.1942592,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-08-langer-teich-immekath": {
    "status": "review",
    "latitude": 52.6277652,
    "longitude": 11.0816699,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-09-neues-gewasser-in-klotze": {
    "status": "review",
    "latitude": 52.622978,
    "longitude": 11.1655101,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-10-teich-am-ehemaligen": {
    "status": "review",
    "latitude": 52.6657464,
    "longitude": 11.1942592,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-11-jeetze-von-dorfstrae-im-amt": {
    "status": "review",
    "latitude": 52.7859661,
    "longitude": 11.1686674,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-12-alte-badeanstalt-bei-jahrstedt": {
    "status": "review",
    "latitude": 52.5633612,
    "longitude": 10.9708505,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-13-dorfteich-steimke": {
    "status": "review",
    "latitude": 52.58744,
    "longitude": 10.963068,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-14-ohre-in-steimke": {
    "status": "review",
    "latitude": 52.6021446,
    "longitude": 10.9490976,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-15-ohre-in-jahrstedt": {
    "status": "review",
    "latitude": 52.5557359,
    "longitude": 10.9815634,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-16-ehemalige-klarteiche-in-kusey": {
    "status": "review",
    "latitude": 52.5802866,
    "longitude": 11.1015091,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-17-radestucken-neuekrug": {
    "status": "review",
    "latitude": 52.7786135,
    "longitude": 10.8198134,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-18-dorfteich-dannefeld": {
    "status": "review",
    "latitude": 52.5076908,
    "longitude": 11.1432105,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-19-groe-rothe-neuferchau": {
    "status": "review",
    "latitude": 52.5785765,
    "longitude": 11.0840948,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-20-untere-milde-cheinitz": {
    "status": "review",
    "latitude": 52.6991031,
    "longitude": 11.2520614,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-21-brookbuschteich-immekath": {
    "status": "review",
    "latitude": 52.6277652,
    "longitude": 11.0816699,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-260-22-moorgraben-cheinitz-bruchau": {
    "status": "unmatched",
    "reason": "Kein OSM-v3-Kandidat zum Gegenprüfen."
  },
  "1-380-01-plattensee-bei-winterfeld": {
    "status": "review",
    "latitude": 52.7421551,
    "longitude": 11.2416101,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-380-02-pfefferteich-bei-salzwedel": {
    "status": "review",
    "latitude": 52.8502074,
    "longitude": 11.1473386,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-380-03-1-tonstich-in-den-beekwiesen": {
    "status": "review",
    "latitude": 52.8518698,
    "longitude": 11.156102,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  },
  "1-380-04-brietzer-teiche": {
    "status": "unmatched",
    "reason": "Kein OSM-v3-Kandidat zum Gegenprüfen."
  },
  "1-380-05-teich-in-langenapel": {
    "status": "review",
    "latitude": 52.8161811,
    "longitude": 10.9622902,
    "reason": "OSM-Kandidat vorhanden, aber kein amtliches HY-P-Objekt im Prüfbereich."
  }
};
