// AUTO-GENERATED by scripts/verify-two-source-v6-2.mjs
// Zweiquellen-Abgleich: OSM-v3 + amtlicher INSPIRE HY-P WFS Sachsen-Anhalt.

export interface TwoSourceWaterV62Match {
  status: "matched" | "review" | "unmatched";
  latitude?: number;
  longitude?: number;
  osmConfidence?: number;
  officialDistanceM?: number;
  officialName?: string;
  officialFeatureId?: string;
  officialType?: "StandingWater" | "Watercourse";
  officialCandidateCount?: number;
  nameScore?: number;
  distanceGapM?: number;
  reason: string;
}

export const twoSourceWaterV62Index: Record<string, TwoSourceWaterV62Match> = {
  "1-160-01-bruders-teich-bei-gardelegen": {
    "status": "review",
    "latitude": 52.5298075,
    "longitude": 11.3967719,
    "osmConfidence": 0.908,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-160-02-wasserspeicher-luffingen": {
    "status": "matched",
    "latitude": 52.5690667,
    "longitude": 11.4038551,
    "osmConfidence": 0.838,
    "officialDistanceM": 21.3,
    "officialFeatureId": "StandingWater_DESTGEOT00003zoS",
    "officialType": "StandingWater",
    "officialCandidateCount": 1,
    "nameScore": 0,
    "distanceGapM": 9999,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-160-03-kieskuhle-die-lange-wohrde": {
    "status": "review",
    "latitude": 52.5298075,
    "longitude": 11.3967719,
    "osmConfidence": 0.908,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-160-04-stadtgraben-in-gardelegen": {
    "status": "review",
    "latitude": 52.5186616,
    "longitude": 11.3838142,
    "osmConfidence": 0.856,
    "officialDistanceM": 27.2,
    "officialFeatureId": "Watercourse_DESTGEOT00003zQr_lin",
    "officialType": "Watercourse",
    "officialCandidateCount": 9,
    "nameScore": 0,
    "distanceGapM": 34.5,
    "reason": "Amtliches Wasserobjekt vorhanden, Abstand/Name aber nicht eindeutig genug."
  },
  "1-160-05-lindenthaler-teich-bei-gardelegen": {
    "status": "review",
    "latitude": 52.5298075,
    "longitude": 11.3967719,
    "osmConfidence": 0.908,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-160-06-wilhelmskanal-von-strae": {
    "status": "unmatched",
    "reason": "Kein OSM-v3-Kandidat vorhanden."
  },
  "1-160-07-rotzen-s-loch-bei-breiteiche": {
    "status": "unmatched",
    "reason": "Kein OSM-v3-Kandidat vorhanden."
  },
  "1-160-08-kiessee-gade-bei-solpke": {
    "status": "matched",
    "latitude": 52.5072174,
    "longitude": 11.3007939,
    "osmConfidence": 0.867,
    "officialDistanceM": 13.2,
    "officialFeatureId": "StandingWater_DESTGEOT00003yGl",
    "officialType": "StandingWater",
    "officialCandidateCount": 6,
    "nameScore": 0,
    "distanceGapM": 82.9,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-160-09-5-teiche-am-ipser-weg": {
    "status": "matched",
    "latitude": 52.5105546,
    "longitude": 11.4031394,
    "osmConfidence": 0.912,
    "officialDistanceM": 16.6,
    "officialFeatureId": "StandingWater_DESTGEOT00003yG6",
    "officialType": "StandingWater",
    "officialCandidateCount": 2,
    "nameScore": 0,
    "distanceGapM": 314.1,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-160-12-mahlbusen-heidberg-bei-estedt": {
    "status": "review",
    "latitude": 52.5774526,
    "longitude": 11.3662233,
    "osmConfidence": 0.913,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-160-13-forsterteich-bei-jerchel": {
    "status": "matched",
    "latitude": 52.4660874,
    "longitude": 11.3160803,
    "osmConfidence": 0.905,
    "officialDistanceM": 18.3,
    "officialFeatureId": "StandingWater_DESTGEOT00003yGj",
    "officialType": "StandingWater",
    "officialCandidateCount": 1,
    "nameScore": 0,
    "distanceGapM": 9999,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-160-14-milde-von-gardelegen": {
    "status": "matched",
    "latitude": 52.5194852,
    "longitude": 11.5303351,
    "osmConfidence": 0.896,
    "officialDistanceM": 8.9,
    "officialFeatureId": "Watercourse_DESTGEOT00003JVp_lin",
    "officialType": "Watercourse",
    "officialCandidateCount": 1,
    "nameScore": 0,
    "distanceGapM": 9999,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-160-15-blechbudenteich-bei": {
    "status": "review",
    "latitude": 52.69358,
    "longitude": 11.4673365,
    "osmConfidence": 0.846,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-160-16-untere-milde-von-wegebrucke": {
    "status": "matched",
    "latitude": 52.7047934,
    "longitude": 11.5078816,
    "osmConfidence": 0.747,
    "officialDistanceM": 0.2,
    "officialFeatureId": "Watercourse_DESTGEOT00003MSM_lin",
    "officialType": "Watercourse",
    "officialCandidateCount": 6,
    "nameScore": 0,
    "distanceGapM": 256,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-160-17-kellerbuschteiche-lindstedt": {
    "status": "review",
    "latitude": 52.5905802,
    "longitude": 11.5322808,
    "osmConfidence": 0.925,
    "officialDistanceM": 425,
    "officialFeatureId": "StandingWater_DESTGEOT00003KQy",
    "officialType": "StandingWater",
    "officialCandidateCount": 1,
    "nameScore": 0,
    "distanceGapM": 9999,
    "reason": "Amtliches Wasserobjekt vorhanden, Abstand/Name aber nicht eindeutig genug."
  },
  "1-160-18-untere-milde-von-straenbrucke": {
    "status": "unmatched",
    "reason": "Kein OSM-v3-Kandidat vorhanden."
  },
  "1-160-19-teich-faule-breite-bei-letzlingen": {
    "status": "review",
    "latitude": 52.4460723,
    "longitude": 11.4729848,
    "osmConfidence": 0.874,
    "officialDistanceM": 86,
    "officialFeatureId": "StandingWater_DESTGEOTR100bqpd",
    "officialType": "StandingWater",
    "officialCandidateCount": 1,
    "nameScore": 0,
    "distanceGapM": 9999,
    "reason": "Amtliche HY-P-Geometrie liegt nahe am OSM-Kandidaten, aber nicht eindeutig genug für automatische Freigabe."
  },
  "1-160-20-konigsgraben-vom-abschlag": {
    "status": "matched",
    "latitude": 52.7047934,
    "longitude": 11.5078816,
    "osmConfidence": 0.747,
    "officialDistanceM": 0.2,
    "officialFeatureId": "Watercourse_DESTGEOT00003MSM_lin",
    "officialType": "Watercourse",
    "officialCandidateCount": 6,
    "nameScore": 0,
    "distanceGapM": 256,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-160-21-kiesgrube-wernitz": {
    "status": "review",
    "latitude": 52.4877963,
    "longitude": 11.2364454,
    "osmConfidence": 0.91,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-160-22-secantsgraben-von-str-br-kalbe-m": {
    "status": "matched",
    "latitude": 52.7047934,
    "longitude": 11.5078816,
    "osmConfidence": 0.747,
    "officialDistanceM": 0.2,
    "officialFeatureId": "Watercourse_DESTGEOT00003MSM_lin",
    "officialType": "Watercourse",
    "officialCandidateCount": 6,
    "nameScore": 0,
    "distanceGapM": 256,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-160-23-grube-minna-bei-kassieck": {
    "status": "review",
    "latitude": 52.5846956,
    "longitude": 11.4873324,
    "osmConfidence": 0.927,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-161-01-teich-am-anglerheim-burggraben": {
    "status": "matched",
    "latitude": 51.773576,
    "longitude": 10.7971424,
    "osmConfidence": 0.937,
    "officialDistanceM": 28.8,
    "officialFeatureId": "Watercourse_DESTGEOT00000CP4_lin",
    "officialType": "Watercourse",
    "officialCandidateCount": 4,
    "nameScore": 0,
    "distanceGapM": 132.2,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-161-02-milde-von-kalbe-straenbrucke": {
    "status": "unmatched",
    "reason": "Kein OSM-v3-Kandidat vorhanden."
  },
  "1-161-03-untere-milde-von-winkelstedt": {
    "status": "review",
    "latitude": 52.677317,
    "longitude": 11.3072696,
    "osmConfidence": 0.914,
    "officialDistanceM": 229.9,
    "officialFeatureId": "Watercourse_DESTGEOT00003BZP_lin",
    "officialType": "Watercourse",
    "officialCandidateCount": 6,
    "nameScore": 0,
    "distanceGapM": 18.1,
    "reason": "Amtliches Wasserobjekt vorhanden, Abstand/Name aber nicht eindeutig genug."
  },
  "1-260-01-dorfteich-miesterhorst": {
    "status": "review",
    "latitude": 52.460807,
    "longitude": 11.1415221,
    "osmConfidence": 0.934,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-260-02-anglerteiche-apenburg": {
    "status": "review",
    "latitude": 52.7100588,
    "longitude": 11.2006718,
    "osmConfidence": 0.914,
    "officialDistanceM": 137,
    "officialFeatureId": "StandingWater_DESTGEOT00003smZ",
    "officialType": "StandingWater",
    "officialCandidateCount": 4,
    "nameScore": 0,
    "distanceGapM": 16.6,
    "reason": "Amtliches Wasserobjekt vorhanden, Abstand/Name aber nicht eindeutig genug."
  },
  "1-260-03-wasserbecken-am-schlammgraben": {
    "status": "matched",
    "latitude": 52.5761761,
    "longitude": 11.0779017,
    "osmConfidence": 0.83,
    "officialDistanceM": 26.6,
    "officialFeatureId": "Watercourse_DESTGEOT00003etv_lin",
    "officialType": "Watercourse",
    "officialCandidateCount": 1,
    "nameScore": 0,
    "distanceGapM": 9999,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-260-04-prozebusch-in-dannefeld": {
    "status": "matched",
    "latitude": 52.5076908,
    "longitude": 11.1432105,
    "osmConfidence": 0.923,
    "officialDistanceM": 24.5,
    "officialFeatureId": "StandingWater_DESTGEOT00003miM",
    "officialType": "StandingWater",
    "officialCandidateCount": 1,
    "nameScore": 0,
    "distanceGapM": 9999,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-260-05-sauergrund-bei-dannefeld": {
    "status": "matched",
    "latitude": 52.5076908,
    "longitude": 11.1432105,
    "osmConfidence": 0.923,
    "officialDistanceM": 24.5,
    "officialFeatureId": "StandingWater_DESTGEOT00003miM",
    "officialType": "StandingWater",
    "officialCandidateCount": 1,
    "nameScore": 0,
    "distanceGapM": 9999,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-260-07-beregnungsteich-bei-lockstedt": {
    "status": "matched",
    "latitude": 52.6657464,
    "longitude": 11.1942592,
    "osmConfidence": 0.892,
    "officialDistanceM": 2.3,
    "officialFeatureId": "StandingWater_DESTGEOT0000ceEL",
    "officialType": "StandingWater",
    "officialCandidateCount": 1,
    "nameScore": 0,
    "distanceGapM": 9999,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-260-08-langer-teich-immekath": {
    "status": "review",
    "latitude": 52.6277652,
    "longitude": 11.0816699,
    "osmConfidence": 0.932,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-260-09-neues-gewasser-in-klotze": {
    "status": "review",
    "latitude": 52.622978,
    "longitude": 11.1655101,
    "osmConfidence": 0.9,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-260-10-teich-am-ehemaligen": {
    "status": "matched",
    "latitude": 52.6657464,
    "longitude": 11.1942592,
    "osmConfidence": 0.892,
    "officialDistanceM": 2.3,
    "officialFeatureId": "StandingWater_DESTGEOT0000ceEL",
    "officialType": "StandingWater",
    "officialCandidateCount": 1,
    "nameScore": 0,
    "distanceGapM": 9999,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-260-11-jeetze-von-dorfstrae-im-amt": {
    "status": "review",
    "latitude": 52.7859661,
    "longitude": 11.1686674,
    "osmConfidence": 0.905,
    "officialDistanceM": 0.7,
    "officialFeatureId": "Watercourse_DESTGEOT00003u5d_lin",
    "officialType": "Watercourse",
    "officialCandidateCount": 14,
    "nameScore": 0,
    "distanceGapM": 6.4,
    "reason": "Amtliches Wasserobjekt vorhanden, Abstand/Name aber nicht eindeutig genug."
  },
  "1-260-12-alte-badeanstalt-bei-jahrstedt": {
    "status": "review",
    "latitude": 52.5633612,
    "longitude": 10.9708505,
    "osmConfidence": 0.906,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-260-13-dorfteich-steimke": {
    "status": "review",
    "latitude": 52.58744,
    "longitude": 10.963068,
    "osmConfidence": 0.921,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-260-14-ohre-in-steimke": {
    "status": "review",
    "latitude": 52.6021446,
    "longitude": 10.9490976,
    "osmConfidence": 0.878,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-260-15-ohre-in-jahrstedt": {
    "status": "matched",
    "latitude": 52.5557359,
    "longitude": 10.9815634,
    "osmConfidence": 0.888,
    "officialDistanceM": 2.5,
    "officialFeatureId": "Watercourse_DESTGEOT00003eoD_lin",
    "officialType": "Watercourse",
    "officialCandidateCount": 7,
    "nameScore": 0,
    "distanceGapM": 107.4,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-260-16-ehemalige-klarteiche-in-kusey": {
    "status": "review",
    "latitude": 52.5802866,
    "longitude": 11.1015091,
    "osmConfidence": 0.909,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-260-17-radestucken-neuekrug": {
    "status": "review",
    "latitude": 52.7786135,
    "longitude": 10.8198134,
    "osmConfidence": 0.841,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-260-18-dorfteich-dannefeld": {
    "status": "matched",
    "latitude": 52.5076908,
    "longitude": 11.1432105,
    "osmConfidence": 0.923,
    "officialDistanceM": 24.5,
    "officialFeatureId": "StandingWater_DESTGEOT00003miM",
    "officialType": "StandingWater",
    "officialCandidateCount": 1,
    "nameScore": 0,
    "distanceGapM": 9999,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-260-19-groe-rothe-neuferchau": {
    "status": "review",
    "latitude": 52.5785765,
    "longitude": 11.0840948,
    "osmConfidence": 0.836,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-260-20-untere-milde-cheinitz": {
    "status": "review",
    "latitude": 52.6991031,
    "longitude": 11.2520614,
    "osmConfidence": 0.916,
    "officialDistanceM": 22.1,
    "officialFeatureId": "Watercourse_DESTGEOT00003rmR_lin",
    "officialType": "Watercourse",
    "officialCandidateCount": 5,
    "nameScore": 0,
    "distanceGapM": 23.9,
    "reason": "Amtliches Wasserobjekt vorhanden, Abstand/Name aber nicht eindeutig genug."
  },
  "1-260-21-brookbuschteich-immekath": {
    "status": "review",
    "latitude": 52.6277652,
    "longitude": 11.0816699,
    "osmConfidence": 0.932,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-260-22-moorgraben-cheinitz-bruchau": {
    "status": "unmatched",
    "reason": "Kein OSM-v3-Kandidat vorhanden."
  },
  "1-380-01-plattensee-bei-winterfeld": {
    "status": "review",
    "latitude": 52.7421551,
    "longitude": 11.2416101,
    "osmConfidence": 0.91,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-380-02-pfefferteich-bei-salzwedel": {
    "status": "matched",
    "latitude": 52.8502074,
    "longitude": 11.1473386,
    "osmConfidence": 0.938,
    "officialDistanceM": 22.9,
    "officialName": "Pfefferteich",
    "officialFeatureId": "StandingWater_DESTGEOT00003uAY",
    "officialType": "StandingWater",
    "officialCandidateCount": 1,
    "nameScore": 0.462,
    "distanceGapM": 9999,
    "reason": "OSM-Kandidat durch amtliche HY-P-Geometrie räumlich bestätigt."
  },
  "1-380-03-1-tonstich-in-den-beekwiesen": {
    "status": "review",
    "latitude": 52.8518698,
    "longitude": 11.156102,
    "osmConfidence": 0.926,
    "officialCandidateCount": 0,
    "reason": "OSM-Kandidat vorhanden, aber im amtlichen Prüfbereich kein passendes HY-P-Objekt gefunden."
  },
  "1-380-04-brietzer-teiche": {
    "status": "unmatched",
    "reason": "Kein OSM-v3-Kandidat vorhanden."
  },
  "1-380-05-teich-in-langenapel": {
    "status": "review",
    "latitude": 52.8161811,
    "longitude": 10.9622902,
    "osmConfidence": 0.914,
    "officialDistanceM": 5,
    "officialFeatureId": "StandingWater_DESTGEOT00003ibC",
    "officialType": "StandingWater",
    "officialCandidateCount": 3,
    "nameScore": 0,
    "distanceGapM": 16.8,
    "reason": "Amtliches Wasserobjekt vorhanden, Abstand/Name aber nicht eindeutig genug."
  }
};
