// AUTO-GENERATED by scripts/enrich-lav-coordinates.mjs
// Review data/lav-coordinate-review.csv before promoting uncertain matches.

export interface LavCoordinateMatch {
  status: "matched" | "review" | "unmatched";
  latitude?: number;
  longitude?: number;
  confidence?: number;
  scoreGap?: number;
  displayName?: string;
  osmType?: string;
  osmId?: number;
  category?: string;
  featureType?: string;
  query?: string;
  checkedAt?: string;
}

export const lavCoordinateIndex: Record<string, LavCoordinateMatch> = {
  "1-160-01-bruders-teich-bei-gardelegen": {
    "status": "unmatched",
    "query": "Brüders Teich bei Gardelegen Sachsen-Anhalt",
    "checkedAt": "2026-08-05T10:08:15.518Z"
  },
  "1-160-02-wasserspeicher-luffingen": {
    "status": "unmatched",
    "query": "Wasserspeicher Lüffingen Sachsen-Anhalt",
    "checkedAt": "2026-08-05T10:08:18.732Z"
  },
  "1-160-03-kieskuhle-die-lange-wohrde": {
    "status": "unmatched",
    "query": "Kieskuhle (Die lange Wohrde) Sachsen-Anhalt",
    "checkedAt": "2026-08-05T10:08:23.446Z"
  },
  "1-160-04-stadtgraben-in-gardelegen": {
    "status": "unmatched",
    "query": "Stadtgraben in Gardelegen Sachsen-Anhalt",
    "checkedAt": "2026-08-05T10:08:26.351Z"
  },
  "1-160-05-lindenthaler-teich-bei-gardelegen": {
    "status": "unmatched",
    "query": "Lindenthaler Teich bei Gardelegen Sachsen-Anhalt",
    "checkedAt": "2026-08-05T10:08:29.132Z"
  },
  "1-160-06-wilhelmskanal-von-strae": {
    "status": "unmatched",
    "query": "Wilhelmskanal von Straße Sachsen-Anhalt",
    "checkedAt": "2026-08-05T10:08:34.081Z"
  },
  "1-160-07-rotzen-s-loch-bei-breiteiche": {
    "status": "unmatched",
    "query": "Rötzen´s Loch bei Breiteiche Sachsen-Anhalt",
    "checkedAt": "2026-08-05T10:08:37.303Z"
  },
  "1-160-08-kiessee-gade-bei-solpke": {
    "status": "unmatched",
    "query": "Kiessee Gäde bei Solpke Sachsen-Anhalt",
    "checkedAt": "2026-08-05T10:08:41.852Z"
  },
  "1-160-09-5-teiche-am-ipser-weg": {
    "status": "unmatched",
    "query": "5 Teiche am Ipser Weg Sachsen-Anhalt",
    "checkedAt": "2026-08-05T10:08:44.704Z"
  },
  "1-160-12-mahlbusen-heidberg-bei-estedt": {
    "status": "unmatched",
    "query": "Mahlbusen-Heidberg bei Estedt Sachsen-Anhalt",
    "checkedAt": "2026-08-05T10:08:47.766Z"
  }
};
