// AUTO-GENERATED by scripts/analyze-local-water-v5.mjs
// v5 nutzt Kandidaten-Eindeutigkeit aus dem v3-Overpass-Cache.

export interface LocalWaterV5Match {
  status: "matched" | "review" | "unmatched";
  tier: "named-unique" | "unnamed-unique" | "unnamed-high" | "named-review" | "unnamed-review" | "flow" | "no-cache" | "none";
  latitude?: number;
  longitude?: number;
  confidence?: number;
  gap?: number;
  nearCount?: number;
  veryNearCount?: number;
  candidateName?: string;
  candidateId?: string;
  distanceKm?: number;
  reason: string;
}

export const localWaterV5Index: Record<string, LocalWaterV5Match> = {
  "1-160-01-bruders-teich-bei-gardelegen": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5298075,
    "longitude": 11.3967719,
    "confidence": 0.964,
    "candidateId": "way/206107973",
    "distanceKm": 0.42,
    "gap": 0.003,
    "nearCount": 23,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-160-02-wasserspeicher-luffingen": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5690667,
    "longitude": 11.4038551,
    "confidence": 0.884,
    "candidateId": "way/87438882",
    "distanceKm": 1.34,
    "gap": 0.124,
    "nearCount": 0,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-160-03-kieskuhle-die-lange-wohrde": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5298075,
    "longitude": 11.3967719,
    "confidence": 0.964,
    "candidateId": "way/206107973",
    "distanceKm": 0.42,
    "gap": 0.003,
    "nearCount": 23,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-160-04-stadtgraben-in-gardelegen": {
    "status": "review",
    "tier": "flow",
    "latitude": 52.5186616,
    "longitude": 11.3838142,
    "confidence": 0.905,
    "candidateId": "way/199340851",
    "distanceKm": 1.1,
    "reason": "Fließgewässer benötigt Abschnittsprüfung."
  },
  "1-160-05-lindenthaler-teich-bei-gardelegen": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5298075,
    "longitude": 11.3967719,
    "confidence": 0.964,
    "candidateId": "way/206107973",
    "distanceKm": 0.42,
    "gap": 0.003,
    "nearCount": 23,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-160-06-wilhelmskanal-von-strae": {
    "status": "unmatched",
    "tier": "none",
    "reason": "Kein v3-Kandidat."
  },
  "1-160-07-rotzen-s-loch-bei-breiteiche": {
    "status": "unmatched",
    "tier": "none",
    "reason": "Kein v3-Kandidat."
  },
  "1-160-08-kiessee-gade-bei-solpke": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5072174,
    "longitude": 11.3007939,
    "confidence": 0.918,
    "candidateId": "way/185076265",
    "distanceKm": 0.95,
    "gap": 0,
    "nearCount": 0,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-160-09-5-teiche-am-ipser-weg": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5105546,
    "longitude": 11.4031394,
    "confidence": 0.969,
    "candidateId": "way/1484289954",
    "distanceKm": 0.36,
    "gap": 0.009,
    "nearCount": 7,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-160-12-mahlbusen-heidberg-bei-estedt": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5774526,
    "longitude": 11.3662233,
    "confidence": 0.969,
    "candidateId": "way/110558895",
    "distanceKm": 0.35,
    "gap": 0.002,
    "nearCount": 3,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-160-13-forsterteich-bei-jerchel": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.4660874,
    "longitude": 11.3160803,
    "confidence": 0.961,
    "candidateId": "way/91124294",
    "distanceKm": 0.45,
    "gap": 0.141,
    "nearCount": 1,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-160-14-milde-von-gardelegen": {
    "status": "review",
    "tier": "flow",
    "latitude": 52.5194852,
    "longitude": 11.5303351,
    "confidence": 0.95,
    "candidateId": "way/978751854",
    "distanceKm": 0.57,
    "reason": "Fließgewässer benötigt Abschnittsprüfung."
  },
  "1-160-15-blechbudenteich-bei": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.69358,
    "longitude": 11.4673365,
    "confidence": 0.894,
    "candidateId": "way/206499747",
    "distanceKm": 1.22,
    "gap": 0.037,
    "nearCount": 0,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-160-16-untere-milde-von-wegebrucke": {
    "status": "review",
    "tier": "flow",
    "latitude": 52.7047934,
    "longitude": 11.5078816,
    "confidence": 0.781,
    "candidateId": "way/985228341",
    "distanceKm": 2.52,
    "reason": "Fließgewässer benötigt Abschnittsprüfung."
  },
  "1-160-17-kellerbuschteiche-lindstedt": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5905802,
    "longitude": 11.5322808,
    "confidence": 0.983,
    "candidateId": "way/1292692273",
    "distanceKm": 0.2,
    "gap": 0.004,
    "nearCount": 4,
    "veryNearCount": 2,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-160-18-untere-milde-von-straenbrucke": {
    "status": "unmatched",
    "tier": "none",
    "reason": "Kein v3-Kandidat."
  },
  "1-160-19-teich-faule-breite-bei-letzlingen": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.4460723,
    "longitude": 11.4729848,
    "confidence": 0.925,
    "candidateId": "way/91322293",
    "distanceKm": 0.86,
    "gap": 0.007,
    "nearCount": 1,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-160-20-konigsgraben-vom-abschlag": {
    "status": "review",
    "tier": "flow",
    "latitude": 52.7047934,
    "longitude": 11.5078816,
    "confidence": 0.781,
    "candidateId": "way/985228341",
    "distanceKm": 2.52,
    "reason": "Fließgewässer benötigt Abschnittsprüfung."
  },
  "1-160-21-kiesgrube-wernitz": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.4877963,
    "longitude": 11.2364454,
    "confidence": 0.966,
    "candidateId": "way/1237610297",
    "distanceKm": 0.39,
    "gap": 0.048,
    "nearCount": 1,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-160-22-secantsgraben-von-str-br-kalbe-m": {
    "status": "review",
    "tier": "flow",
    "latitude": 52.7047934,
    "longitude": 11.5078816,
    "confidence": 0.781,
    "candidateId": "way/985228341",
    "distanceKm": 2.52,
    "reason": "Fließgewässer benötigt Abschnittsprüfung."
  },
  "1-160-23-grube-minna-bei-kassieck": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5846956,
    "longitude": 11.4873324,
    "confidence": 0.985,
    "candidateId": "way/980844977",
    "distanceKm": 0.17,
    "gap": 0.026,
    "nearCount": 2,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-161-01-teich-am-anglerheim-burggraben": {
    "status": "review",
    "tier": "flow",
    "latitude": 51.773576,
    "longitude": 10.7971424,
    "confidence": 0.996,
    "candidateId": "way/206321431",
    "distanceKm": 0.04,
    "reason": "Fließgewässer benötigt Abschnittsprüfung."
  },
  "1-161-02-milde-von-kalbe-straenbrucke": {
    "status": "unmatched",
    "tier": "none",
    "reason": "Kein v3-Kandidat."
  },
  "1-161-03-untere-milde-von-winkelstedt": {
    "status": "review",
    "tier": "flow",
    "latitude": 52.677317,
    "longitude": 11.3072696,
    "confidence": 0.971,
    "candidateId": "way/203635922",
    "distanceKm": 0.34,
    "reason": "Fließgewässer benötigt Abschnittsprüfung."
  },
  "1-260-01-dorfteich-miesterhorst": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.460807,
    "longitude": 11.1415221,
    "confidence": 0.994,
    "candidateId": "way/813601903",
    "distanceKm": 0.07,
    "gap": 0.073,
    "nearCount": 1,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-02-anglerteiche-apenburg": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.7100588,
    "longitude": 11.2006718,
    "confidence": 0.971,
    "candidateId": "way/664885704",
    "distanceKm": 0.33,
    "gap": 0.006,
    "nearCount": 6,
    "veryNearCount": 2,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-03-wasserbecken-am-schlammgraben": {
    "status": "review",
    "tier": "flow",
    "latitude": 52.5761761,
    "longitude": 11.0779017,
    "confidence": 0.876,
    "candidateId": "way/181581843",
    "distanceKm": 1.44,
    "reason": "Fließgewässer benötigt Abschnittsprüfung."
  },
  "1-260-04-prozebusch-in-dannefeld": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5076908,
    "longitude": 11.1432105,
    "confidence": 0.98,
    "candidateId": "way/143621722",
    "distanceKm": 0.23,
    "gap": 0.079,
    "nearCount": 1,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-05-sauergrund-bei-dannefeld": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5076908,
    "longitude": 11.1432105,
    "confidence": 0.98,
    "candidateId": "way/143621722",
    "distanceKm": 0.23,
    "gap": 0.079,
    "nearCount": 1,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-07-beregnungsteich-bei-lockstedt": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.6657464,
    "longitude": 11.1942592,
    "confidence": 0.946,
    "candidateId": "way/490508906",
    "distanceKm": 0.63,
    "gap": 0.045,
    "nearCount": 1,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-08-langer-teich-immekath": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.6277652,
    "longitude": 11.0816699,
    "confidence": 0.991,
    "candidateId": "way/237355615",
    "distanceKm": 0.11,
    "gap": 0.036,
    "nearCount": 9,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-09-neues-gewasser-in-klotze": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.622978,
    "longitude": 11.1655101,
    "confidence": 0.955,
    "candidateId": "relation/3193700",
    "distanceKm": 0.52,
    "gap": 0.019,
    "nearCount": 2,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-10-teich-am-ehemaligen": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.6657464,
    "longitude": 11.1942592,
    "confidence": 0.946,
    "candidateId": "way/490508906",
    "distanceKm": 0.63,
    "gap": 0.045,
    "nearCount": 1,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-11-jeetze-von-dorfstrae-im-amt": {
    "status": "review",
    "tier": "flow",
    "latitude": 52.7859661,
    "longitude": 11.1686674,
    "confidence": 0.961,
    "candidateId": "way/999269699",
    "distanceKm": 0.45,
    "reason": "Fließgewässer benötigt Abschnittsprüfung."
  },
  "1-260-12-alte-badeanstalt-bei-jahrstedt": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5633612,
    "longitude": 10.9708505,
    "confidence": 0.962,
    "candidateId": "way/1228484869",
    "distanceKm": 0.44,
    "gap": 0.008,
    "nearCount": 3,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-13-dorfteich-steimke": {
    "status": "review",
    "tier": "unnamed-high",
    "latitude": 52.58744,
    "longitude": 10.963068,
    "confidence": 0.979,
    "candidateId": "way/1314475633",
    "distanceKm": 0.24,
    "gap": 0.133,
    "nearCount": 1,
    "veryNearCount": 1,
    "reason": "Sehr plausibler unbenannter Kandidat, aber automatische Schwelle knapp nicht erreicht."
  },
  "1-260-14-ohre-in-steimke": {
    "status": "review",
    "tier": "flow",
    "latitude": 52.6021446,
    "longitude": 10.9490976,
    "confidence": 0.915,
    "candidateName": "Ohre",
    "candidateId": "way/164088814",
    "distanceKm": 1.96,
    "reason": "Fließgewässer benötigt Abschnittsprüfung."
  },
  "1-260-15-ohre-in-jahrstedt": {
    "status": "review",
    "tier": "flow",
    "latitude": 52.5557359,
    "longitude": 10.9815634,
    "confidence": 0.942,
    "candidateId": "way/188212172",
    "distanceKm": 0.67,
    "reason": "Fließgewässer benötigt Abschnittsprüfung."
  },
  "1-260-16-ehemalige-klarteiche-in-kusey": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5802866,
    "longitude": 11.1015091,
    "confidence": 0.965,
    "candidateId": "way/226972452",
    "distanceKm": 0.41,
    "gap": 0.005,
    "nearCount": 4,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-17-radestucken-neuekrug": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.7786135,
    "longitude": 10.8198134,
    "confidence": 0.888,
    "candidateId": "way/924865132",
    "distanceKm": 1.3,
    "gap": 0.021,
    "nearCount": 1,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-18-dorfteich-dannefeld": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5076908,
    "longitude": 11.1432105,
    "confidence": 0.98,
    "candidateId": "way/143621722",
    "distanceKm": 0.23,
    "gap": 0.079,
    "nearCount": 1,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-19-groe-rothe-neuferchau": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5785765,
    "longitude": 11.0840948,
    "confidence": 0.883,
    "candidateId": "way/186543484",
    "distanceKm": 1.36,
    "gap": 0.01,
    "nearCount": 0,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-20-untere-milde-cheinitz": {
    "status": "review",
    "tier": "flow",
    "latitude": 52.6991031,
    "longitude": 11.2520614,
    "confidence": 0.973,
    "candidateId": "way/1176907729",
    "distanceKm": 0.31,
    "reason": "Fließgewässer benötigt Abschnittsprüfung."
  },
  "1-260-21-brookbuschteich-immekath": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.6277652,
    "longitude": 11.0816699,
    "confidence": 0.991,
    "candidateId": "way/237355615",
    "distanceKm": 0.11,
    "gap": 0.036,
    "nearCount": 9,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-260-22-moorgraben-cheinitz-bruchau": {
    "status": "unmatched",
    "tier": "none",
    "reason": "Kein v3-Kandidat."
  },
  "1-380-01-plattensee-bei-winterfeld": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.7421551,
    "longitude": 11.2416101,
    "confidence": 0.966,
    "candidateId": "way/198635128",
    "distanceKm": 0.39,
    "gap": 0.058,
    "nearCount": 1,
    "veryNearCount": 0,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-380-02-pfefferteich-bei-salzwedel": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5298075,
    "longitude": 11.3967719,
    "confidence": 0.964,
    "candidateId": "way/206107973",
    "distanceKm": 0.42,
    "gap": 0.003,
    "nearCount": 23,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-380-03-1-tonstich-in-den-beekwiesen": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.5298075,
    "longitude": 11.3967719,
    "confidence": 0.964,
    "candidateId": "way/206107973",
    "distanceKm": 0.42,
    "gap": 0.003,
    "nearCount": 23,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  },
  "1-380-04-brietzer-teiche": {
    "status": "unmatched",
    "tier": "none",
    "reason": "Kein v3-Kandidat."
  },
  "1-380-05-teich-in-langenapel": {
    "status": "review",
    "tier": "unnamed-review",
    "latitude": 52.8161811,
    "longitude": 10.9622902,
    "confidence": 0.971,
    "candidateId": "way/227100010",
    "distanceKm": 0.34,
    "gap": 0.002,
    "nearCount": 4,
    "veryNearCount": 1,
    "reason": "Mehrere plausible Wasserobjekte oder kein ausreichender Vorsprung."
  }
};
